---
kind: Pod
apiVersion: v1
metadata:
  name: keepalived
  namespace: openshift-{{ onPremPlatformShortName .ControllerConfig }}-infra
  deletionGracePeriodSeconds: 65
  labels:
    app: '{{ onPremPlatformShortName .ControllerConfig }}-infra-bgp'
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  volumes:
  - name: resource-dir
    hostPath:
      path: "/etc/kubernetes/static-pod-resources/frr"
  - name: kubeconfig
    hostPath:
      path: "/etc/kubernetes/kubeconfig"
  - name: conf-dir
    hostPath:
      path: "/etc/frr"
  - name: manifests
    hostPath:
      path: "/opt/openshift/manifests"
  - name: run-dir
    empty-dir: {}
  initContainers:
  - name: render-config
    image: {{ .Images.BaremetalRuntimeCfgBootstrap }}
    command:
    # {{ with $bgp := onPremPlatformBGPConfiguration .FailureDomainName }}
    - runtimecfg 
    - render
    - "/etc/kubernetes/kubeconfig"
    - "--bgp-neighbours"
    - '{{ $bgp.Neighbours }}'
    - "--bgp-asn"
    - '{{ $bgp.ASN }}'
    - "--bgp-password"
    - '{{ $bgp.Password }}'
    - "/config"
    - "--out-dir"
    - "/etc/frr"
    - "--cluster-config"
    - "/opt/openshift/manifests/cluster-config.yaml"
    # {{ end }}
    resources: {}
    volumeMounts:
    - name: kubeconfig
      mountPath: "/etc/kubernetes/kubeconfig"
    - name: resource-dir
      mountPath: "/config"
    - name: conf-dir
      mountPath: "/etc/frr"
    - name: manifests
      mountPath: "/opt/openshift/manifests"
    imagePullPolicy: IfNotPresent
  containers:
  - name: frr
    securityContext:
      privileged: true
    image: docker.io/frrouting/frr
    env:
      - name: NSS_SDB_USE_CACHE
        value: "no"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/frr"
    - name: run-dir
      mountPath: "/var/run/frr"
    livenessProbe:
      exec:
        command:
        - vtysh
        - -c
        - show bfd peers
      initialDelaySeconds: 20
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  - name: frr-api-vip
    # change me, we probably don't need this image but I picked this one for now:
    image: quay.io/emilien/stolostron-builder:bgp
    securityContext:
      privileged: true
    # We'll need to make it smarter with a script that tear down the VIP if the masters are up.
    command:
    - /bin/bash
    - -c
    - |
      #/bin/bash
      
      API_VIP="{{ .Cluster.APIVIP }}"
      VIP_NETMASK="{{ .Cluster.VIPNetmask }}"

      ip address add $API_VIP/$VIP_NETMASK dev lo
      echo "VIP $API_VIP/$VIP_NETMASK was created on this node"

      CURL_MAX_TIME="${CURL_MAX_TIME:-2}"
      
      check_health() {
          # check if the service is healthy if a curl returns 200.
          # return 0 if healthy, 1 if not.
          # takes one argument: the URL to check.
          url=$1
          RESPONSE=$(/usr/bin/curl --max-time $CURL_MAX_TIME -o /dev/null -kLfs -w "%{http_code}\n" $url)
          if test ${RESPONSE} -eq 200; then
              echo "Health check passed for $url"
              return 0
          else
              echo "Health check failed for $url, curl returned $RESPONSE"
              return 1
          fi
      }
      
      check_vip() {
          # check if the VIP is assigned to this node.
          # return 0 if it is, 1 if not.
          # takes one argument: the VIP to check.
          vip=$1
          if /sbin/ip address show dev lo | grep -q $vip; then
              echo "VIP $vip is assigned to this node"
              return 0
          else
              echo "VIP $vip is not assigned to this node"
              return 1
          fi
      }
      
      delete_vip() {
          # delete the VIP on the node.
          # takes one argument: the VIP to delete.
          vip=$1
          echo "Deleting VIP $vip"
          /sbin/ip address del $vip/32 dev lo
      }
      
      list_healthy_masters() {
          # List all healthy masters
          masterNodesReady=$(oc get nodes -l node-role.kubernetes.io/master | grep "Ready" | awk '{ print $1 }')
          for master in $masterNodesReady; do
              echo "$master node is Ready"
              masterInternalIP=(oc get node/$master -o 'jsonpath={.status.addresses[?(@.type=="InternalIP")].address}')
              if check_health "https://$masterInternalIP:6443/readyz"; then
                  echo "$master node is healthy"
                  return 0
              fi
          done
          echo "No healthy master nodes found"
          return 1
      }
      
      while :; do
          if list_healthy_masters; then
              echo "At least one healthy master node found"
              if check_vip $API_VIP; then
                  delete_vip $API_VIP/$VIP_NETMASK
                  echo "VIP $API_VIP/$VIP_NETMASK deleted, exiting"
                  exit 0
              fi
          fi
      done
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  # - name: keepalived-monitor
  #   image: {{ .Images.BaremetalRuntimeCfgBootstrap }}
  #   env:
  #     - name: ENABLE_UNICAST
  #       value: "yes"
  #     - name: IS_BOOTSTRAP
  #       value: "yes"
  #   command:
  #   - dynkeepalived
  #   - "/etc/kubernetes/kubeconfig"
  #   - "/config/keepalived.conf.tmpl"
  #   - "/etc/keepalived/keepalived.conf"
  #   - "--api-vip"
  #   - "{{ onPremPlatformAPIServerInternalIP .ControllerConfig }}"
  #   - "--ingress-vip"
  #   - "{{ onPremPlatformIngressIP .ControllerConfig }}"
  #   - "--cluster-config"
  #   - "/opt/openshift/manifests/cluster-config.yaml"
  #   - "--check-interval"
  #   - "5s"
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 200Mi
  #   volumeMounts:
  #   - name: resource-dir
  #     mountPath: "/config"
  #   - name: kubeconfig
  #     mountPath: "/etc/kubernetes/kubeconfig"
  #   - name: conf-dir
  #     mountPath: "/etc/keepalived"
  #   - name: run-dir
  #     mountPath: "/var/run/keepalived"
  #   - name: manifests
  #     mountPath: "/opt/openshift/manifests"
  #   imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
